import React from 'react';
import { Route, Link } from 'react-router-dom';
import ContentEditable from 'react-sane-contenteditable';
import NotFound from './NotFound';

class Menu extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};

        this.getCocktails()
    }

    componentDidUpdate(prevProps, prevState) {
        if (prevProps !== this.props) {
            this.getCocktails();
        }
    }

    getCocktails() {
        if (!this.props.cocktailIds) {
            return;
        }

        fetch('/Menu/Data?' + this.props.cocktailIds.map(c => 'c=' + c).join('&'))
            .then(response => {
                if (response.status == 200) {
                    response.json().then(cocktails => {
                        this.setState({ cocktails });
                    });
                }
            });
    }

    render() {
        if (!this.props.name) {
            return <NotFound />;
        }

        document.title = this.props.name + ' - Miksd';

        return (
            <div>
                <div className="menu">
                    <ContentEditable
                        content={this.props.name}
                        editable={!!this.props.handleRenameMenu}
                        onChange={(e, value) => this.props.handleRenameMenu(this.props.id, value)}
                        tagName="h2"
                    />
                    <dl>
                        {this.state.cocktails && this.state.cocktails.map(c =>
                            <div key={c.id}>
                                <dt><Link to={"/Cocktail/" + c.id}>{c.name}</Link></dt>
                                <dd>{c.recipe.join(', ')}</dd>
                            </div>
                        )}
                    </dl>
                </div>
                <Route path='/Menu/View' component={Footer} />
            </div>
        );
    }
}

const Footer = () => (
    <div className='footer'>
        <hr />
        <div>Menu generated by <Link to='/' className='link'>Miksd</Link></div>
    </div>
);

export default Menu;