import React from 'react';
import { Route, Link } from 'react-router-dom';
import ContentEditable from 'react-sane-contenteditable';
import NotFound from './NotFound';

class Menu extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};

        this.getCocktails()
    }

    componentDidUpdate(prevProps, prevState) {
        if (prevProps !== this.props) {
            this.getCocktails();
        }
    }

    getCocktails() {
        if (!this.props.cocktailIds) {
            return;
        }

        fetch('/Menu/Data?' + this.props.cocktailIds.map(c => 'c=' + c).join('&'))
            .then(response => {
                if (response.status == 200) {
                    response.json().then(cocktails => {
                        this.setState({ cocktails });
                    });
                }
            });
    }

    render() {
        if (!this.props.name) {
            return <NotFound />;
        }

        document.title = this.props.name + ' - Miksd';

        const cocktailList = !this.state.cocktails ? null : !this.state.cocktails.length ? (
            <p>
                No cocktails have been added to this menu yet.<br />
                Go <Link to='/' className='link'>check out some cocktails</Link> and add them!
            </p>
        ): (
            <dl>
                {this.state.cocktails.map(c =>
                    <div key={c.id}>
                        <dt>
                            <Link to={"/Cocktail/" + c.id}>{c.name}</Link>
                            {!this.props.handleRemoveCocktailFromMenu ? null :
                                <span className="remove-menu-button"
                                    onClick={() => this.props.handleRemoveCocktailFromMenu(this.props.id, c.id)}
                                >
                                    −
                                </span>
                            }
                        </dt>
                        <dd>{c.recipe.join(', ')}</dd>
                    </div>
                )}
            </dl>
        );

        return (
            <div>
                <div className="menu">
                    <ContentEditable
                        content={this.props.name}
                        editable={!!this.props.handleRenameMenu}
                        onChange={(e, value) => this.props.handleRenameMenu(this.props.id, value)}
                        tagName="h2"
                    />
                    {cocktailList}
                </div>
                <Route path='/Menu/View' component={Footer} />
            </div>
        );
    }
}

const Footer = () => (
    <div className='footer'>
        <hr />
        <div>Menu generated by <Link to='/' className='link'>Miksd</Link></div>
    </div>
);

export default Menu;