using System.Collections.Generic;

using C = Mix.Models.Cocktail;
using CI = Mix.Models.CocktailIngredient;
using q = Mix.Models.CommonQuantity;
using i = Mix.Models.Ingredients;
using c = Mix.Models.Cocktails;
using v = Mix.Models.Vessels;
using p = Mix.Models.PrepMethods;
using g = Mix.Models.Garnishes;
using s = Mix.Models.SpecialPreps;

namespace Mix.Models
{
    public static partial class Reference
    {
        private const bool onTheRocks = true;

        public static List<Cocktail> AllCocktails = new List<Cocktail>
        {
            new C(c.Americano, "Americano", "#B40002", onTheRocks,
                v.Rocks, p.Build, g.OrangeSlice,
                new CI(i.Campari, 30M),
                new CI(i.SweetVermouth, 30M),
                new CI(i.Soda, q.Splash)),

            new C(c.Daiquiri, "Daiquiri", "#DFD774",
                v.Cocktail, p.Shake, g.None,
                new CI(i.WhiteRum, 45M),
                new CI(i.SimpleSyrup, 15M),
                new CI(i.LimeJuice, 25M)),

            new C(c.Martini, "Martini", "#E9E9E9",
                v.Cocktail, p.Stir, g.Olive,
                new CI(i.Gin, 60M),
                new CI(i.DryVermouth, 10M)),

            new C(c.Manhattan, "Manhattan", "#B70001",
                v.Cocktail, p.Stir, g.Cherry,
                new CI(i.Rye, 50M),
                new CI(i.SweetVermouth, 20M),
                new CI(i.Angostura, q.Dash)),

            new C(c.Martinez, "Martinez", "#AC2102",
                v.Cocktail, p.Stir, g.OrangeTwist,
                new CI(i.OldTom, 50M),
                new CI(i.SweetVermouth, 30M),
                new CI(i.Maraschino, q.Teaspoon),
                new CI(i.Angostura, q.Dash)),

            new C(c.Negroni, "Negroni", "#A71701", onTheRocks,
                v.Rocks, p.Build, g.OrangeSlice,
                new CI(i.Gin, 30M),
                new CI(i.Campari, 30M),
                new CI(i.SweetVermouth, 30M)),

            new C(c.Boulevardier, "Boulevardier", "#B42210", onTheRocks,
                v.Rocks, p.Stir, g.OrangeTwist,
                new CI(i.Bourbon, 30M),
                new CI(i.Campari, 30M),
                new CI(i.SweetVermouth, 30M)),

            new C(c.OldFashioned, "Old Fashioned", "#BB360E", onTheRocks,
                v.Rocks, p.Build, g.OrangeTwist,
                new CI(i.BourbonOrRye, 45M),
                new CI(i.Angostura, 2 * q.Dash),
                new CI(i.Sugar, q.Teaspoon),
                new CI(i.Water, q.Splash)),

            new C(c.WhiskeySour, "Whiskey Sour", "#EEA501",
                v.Cocktail, p.Shake, g.None,
                new CI(i.Bourbon, 45M),
                new CI(i.SimpleSyrup, 15M),
                new CI(i.LemonJuice, 30M),
                new CI(i.EggWhite, q.Splash, isOptional: true)),

            new C(c.PiscoSour, "Pisco Sour", "#D6C37B",
                v.Rocks, p.Shake, g.None,
                new CI(i.Pisco, 45M),
                new CI(i.SimpleSyrup, 20M),
                new CI(i.LemonJuice, 30M),
                new CI(i.EggWhite, q.Splash, isOptional: true)),

            new C(c.Aviation, "Aviation", "#9886C4",
                v.Cocktail, p.Shake, g.Cherry,
                new CI(i.Gin, 45M),
                new CI(i.Maraschino, 15M),
                new CI(i.LemonJuice, 15M),
                new CI(i.Violette, 7.5M)),

            new C(c.Bacardi, "Bacardi", "#C21F1E",
                v.Cocktail, p.Shake, g.None,
                new CI(i.WhiteRum, 45M),
                new CI(i.LimeJuice, 20M),
                new CI(i.Grenadine, 10M)),

            new C(c.BetweenTheSheets, "Between the Sheets", "#BC7B21",
                v.Cocktail, p.Shake, g.None,
                new CI(i.Cognac, 30M),
                new CI(i.WhiteRum, 30M),
                new CI(i.TripleSec, 30M),
                new CI(i.LemonJuice, 20M)),

            new C(c.Casino, "Casino", "#D9E3DB",
                v.Cocktail, p.Shake, g.Cherry,
                new CI(i.OldTom, 40M),
                new CI(i.Maraschino, 10M),
                new CI(i.OrangeBitters, 10M),
                new CI(i.LemonJuice, 10M)),

            new C(c.GinFizz, "Gin Fizz", "#DFE5D7", onTheRocks,
                v.Highball, p.Shake, g.LemonSlice,
                new CI(i.Gin, 45M),
                new CI(i.SimpleSyrup, 10M),
                new CI(i.LemonJuice, 30M),
                new CI(i.Soda, 80)),

            new C(c.TomCollins, "Tom Collins", "#F4F1B5", onTheRocks,
                v.Highball, p.Build, g.LemonSlice,
                new CI(i.OldTom, 45M),
                new CI(i.SimpleSyrup, 15M),
                new CI(i.LemonJuice, 30M),
                new CI(i.Soda, 60M)),

            new C(c.MonkeyGland, "Monkey Gland", "#DB4208",
                v.Cocktail, p.Shake, g.None,
                new CI(i.Gin, 50M),
                new CI(i.OrangeJuice, 30M),
                new CI(i.Absinthe, q.Splash),
                new CI(i.Grenadine, q.Splash)),

            new C(c.PlantersPunch, "Planter's Punch", "#FE4501", onTheRocks,
                v.Highball, p.Shake, g.OrangeSlice,
                new CI(i.DarkRum, 45M),
                new CI(i.OrangeJuice, 35),
                new CI(i.PineappleJuice, 35),
                new CI(i.LemonJuice, 20M),
                new CI(i.Grenadine, 10M),
                new CI(i.SimpleSyrup, 10M),
                new CI(i.Angostura, 3 * q.Dash)),

            new C(c.RustyNail, "Rusty Nail", "#7D1D00", onTheRocks,
                v.Rocks, p.Build, g.None,
                new CI(i.Scotch, 45M),
                new CI(i.Drambuie, 25M)),

            new C(c.Sazerac, "Sazerac", "#AA1705",
                v.Rocks, p.Stir, g.LemonTwist,
                new CI(i.CognacOrRye, 50M),
                new CI(i.Absinthe, 10M, s.Rinse),
                new CI(i.Sugar, q.Teaspoon),
                new CI(i.Peychauds, 2 * q.Dash)),

            new C(c.Screwdriver, "Screwdriver", "#FFD603", onTheRocks,
                v.Highball, p.Build, g.OrangeSlice,
                new CI(i.Vodka, 50M),
                new CI(i.OrangeJuice, 10M)),

            new C(c.Sidecar, "Sidecar", "#BB6802",
                v.Cocktail, p.Shake, g.LemonTwist,
                new CI(i.Cognac, 50M),
                new CI(i.TripleSec, 20M),
                new CI(i.LemonJuice, 20M)),

            new C(c.Tuxedo, "Tuxedo", "#B58F41",
                v.Cocktail, p.Stir, g.LemonTwist | g.Cherry,
                new CI(i.OldTom, 30M),
                new CI(i.DryVermouth, 30M),
                new CI(i.Maraschino, q.Teaspoon / 2),
                new CI(i.Absinthe, q.Teaspoon / 4),
                new CI(i.OrangeBitters, 3 * q.Dash)),

            new C(c.WhiteLady, "White Lady", "#FDFAD4",
                v.Cocktail, p.Shake, g.None,
                new CI(i.Gin, 40M),
                new CI(i.TripleSec, 30M),
                new CI(i.LemonJuice, 20M)),

            new C(c.LemonDrop, "Lemon Drop", "#FEDC5E",
                v.Cocktail, p.Shake, g.LemonSlice,
                new CI(i.Vodka, 25M),
                new CI(i.TripleSec, 20M),
                new CI(i.LemonJuice, 15M)),

            new C(c.Cosmopolitan, "Cosmopolitan", "#E9211B",
                v.Cocktail, p.Shake, g.OrangeTwist,
                new CI(i.Vodka, 40M),
                new CI(i.Cointreau, 15M),
                new CI(i.CranberryJuice, 30M),
                new CI(i.LimeJuice, 15M)),

            new C(c.CubaLibre, "Cuba Libre", "#7B340B", onTheRocks,
                v.Highball, p.Build, g.LimeWedge,
                new CI(i.WhiteRum, 50M),
                new CI(i.Cola, 120M),
                new CI(i.LimeJuice, 10M)),

            new C(c.MoscowMule, "Moscow Mule", "#B26B2F", onTheRocks,
                v.Highball, p.Build, g.LimeWedge,
                new CI(i.Vodka, 45M),
                new CI(i.GingerBeer, 120M),
                new CI(i.LimeJuice, 5M)),

            new C(c.GinAndTonic, "Gin and Tonic", "#E4E8D5", onTheRocks,
                v.Highball, p.Build, g.LimeWedge,
                new CI(i.Gin, 50M),
                new CI(i.Tonic, 120M)),

            new C(c.DarkNStormy, "Dark N Stormy", "#B24505", onTheRocks,
                v.Highball, p.Build, g.LimeWedge,
                new CI(i.DarkRum, 60M),
                new CI(i.GingerBeer, 90M)),

            new C(c.Margarita, "Margarita", "#C7BC57",
                v.Cocktail, p.Shake, g.None,
                new CI(i.Tequila, 35M),
                new CI(i.Cointreau, 20M),
                new CI(i.LimeJuice, 15M)),

            new C(c.Sunrise, "Tequila Sunrise", "#D52027,#EAB938", onTheRocks,
                v.Highball, p.Build, g.OrangeSlice | g.Cherry,
                new CI(i.Tequila, 45M),
                new CI(i.OrangeJuice, 90M),
                new CI(i.Grenadine, 15M)),

            new C(c.Kamikaze, "Kamikaze", "#DEE29F",
                v.Cocktail, p.Shake, g.LimeSlice,
                new CI(i.Vodka, 30M),
                new CI(i.TripleSec, 30M),
                new CI(i.LimeJuice, 30M)),

            new C(c.Kir, "Kir", "#FD2A0D",
                v.Flute, p.Build, g.None,
                new CI(i.WhiteWine, 90M),
                new CI(i.Cassis, 10M)),

            new C(c.Bellini, "Bellini", "#DDA231",
                v.Flute, p.Build, g.None,
                new CI(i.Prosecco, 100M),
                new CI(i.PeachPuree, 50M)),

            new C(c.ChampagneCocktail, "Champagne Cocktail", "#F5DB9D",
                v.Flute, p.Build, g.OrangeTwist,
                new CI(i.Champagne, 90M),
                new CI(i.Cognac, 10M),
                new CI(i.Angostura, 2 * q.Dash),
                new CI(i.Sugar, q.Teaspoon)),

            new C(c.Mimosa, "Mimosa", "#FEC506",
                v.Flute, p.Build, g.OrangeTwist,
                new CI(i.Champagne, 75M),
                new CI(i.OrangeJuice, 75M)),

            new C(c.French75, "French 75", "#F7E4B1",
                v.Flute, p.Shake, g.None,
                new CI(i.Gin, 30M),
                new CI(i.Champagne, 60M),
                new CI(i.LemonJuice, 15M),
                new CI(i.SimpleSyrup, 2 * q.Dash)),

            new C(c.FrenchConnection, "French Connection", "#D79D28", onTheRocks,
                v.Rocks, p.Build, g.None,
                new CI(i.Cognac, 35M),
                new CI(i.Amaretto, 35M)),

            new C(c.Godfather, "Godfather", "#D57B20", onTheRocks,
                v.Rocks, p.Build, g.None,
                new CI(i.Scotch, 35M),
                new CI(i.Amaretto, 35M)),

            new C(c.Godmother, "Godmother", "#D98D3C", onTheRocks,
                v.Rocks, p.Build, g.None,
                new CI(i.Vodka, 35M),
                new CI(i.Amaretto, 35M)),

            new C(c.SeaBreeze, "Sea Breeze", "#E0412B", onTheRocks,
                v.Highball, p.Build, g.LimeSlice,
                new CI(i.Vodka, 45M),
                new CI(i.CranberryJuice, 90M),
                new CI(i.GrapefruitJuice, 30M)),

            new C(c.MaryPickford, "Mary Pickford", "#DF5637",
                v.Cocktail, p.Shake, g.None,
                new CI(i.WhiteRum, 60M),
                new CI(i.PineappleJuice, 60M),
                new CI(i.Grenadine, 10M),
                new CI(i.Maraschino, 10M)),

            new C(c.BlackRussian, "Black Russian", "#68040A", onTheRocks,
                v.Rocks, p.Build, g.None,
                new CI(i.Vodka, 50M),
                new CI(i.Kahlúa, 20M)),

            new C(c.WhiteRussian, "White Russian", "#68040A,#68040A,#B6A381", onTheRocks,
                v.Rocks, p.Build, g.None,
                new CI(i.Vodka, 50M),
                new CI(i.Kahlúa, 20M),
                new CI(i.Cream, 30M, s.Float)),

            new C(c.LongIsland, "Long Island Iced Tea", "#92392A", onTheRocks,
                v.Highball, p.Build, g.None,
                new CI(i.Tequila, 15M),
                new CI(i.Vodka, 15M),
                new CI(i.Gin, 15M),
                new CI(i.WhiteRum, 15M),
                new CI(i.TripleSec, 15M),
                new CI(i.LemonJuice, 25M),
                new CI(i.GommeSyrup, 30M),
                new CI(i.Cola, q.Dash)),

            new C(c.HemingwaySpecial, "Hemingway Special", "#EFBD47",
                v.Cocktail, p.Shake, g.None,
                new CI(i.WhiteRum, 60M),
                new CI(i.GrapefruitJuice, 40M),
                new CI(i.LimeJuice, 15M),
                new CI(i.Maraschino, 15M)),

            new C(c.HarveyWallbanger, "Harvey Wallbanger", "#F49801", onTheRocks,
                v.Highball, p.Build, g.OrangeSlice,
                new CI(i.Vodka, 45M),
                new CI(i.Galliano, 15M, s.Float),
                new CI(i.OrangeJuice, 90M)),

            new C(c.GoldenDream, "Golden Dream", "#E6BC29",
                v.Cocktail, p.Shake, g.None,
                new CI(i.Galliano, 20M),
                new CI(i.TripleSec, 20M),
                new CI(i.OrangeJuice, 20M),
                new CI(i.Cream, 10M)),

            new C(c.VieuxCarré, "Vieux Carré", "#C81F03", onTheRocks,
                v.Rocks, p.Stir, g.LemonTwist,
                new CI(i.BourbonOrRye, 60M),
                new CI(i.Cognac, 60M),
                new CI(i.SweetVermouth, 60M),
                new CI(i.Benedictine, q.Teaspoon),
                new CI(i.Angostura, q.Dash),
                new CI(i.Peychauds, q.Dash)),

            new C(c.Mojito, "Mojito", "#C9C3C0", onTheRocks,
                v.Highball, p.Build, g.None,
                new CI(i.WhiteRum, 50M),
                new CI(i.LimeJuice, 30M),
                new CI(i.MintLeaf, 12, s.Muddle),
                new CI(i.Sugar, 2 * q.Teaspoon),
                new CI(i.Soda, 120M)),

            new C(c.MintJulep, "Mint Julep", "#EAB339", onTheRocks,
                v.Highball, p.Build, g.None,
                new CI(i.Bourbon, 60M),
                new CI(i.MintLeaf, 12, s.Muddle),
                new CI(i.SimpleSyrup, 15M)),

            new C(c.Gimlet, "Gimlet", "#C8CF9D",
                v.Cocktail, p.Shake, g.LimeSlice,
                new CI(i.Gin, 60M),
                new CI(i.LimeCordial, 20M)),

            new C(c.MaiTai, "Mai Tai", "#FD9523", onTheRocks,
                v.Rocks, p.Shake, g.LimeWedge | g.Cherry,
                new CI(i.WhiteRum, 40M),
                new CI(i.DarkRum, 20M),
                new CI(i.Curaçao, 15),
                new CI(i.Orgeat, 15),
                new CI(i.LimeJuice, 10M)),

            new C(c.PiñaColada, "Piña Colada", "#E4D1A6", onTheRocks,
                v.Highball, p.Shake, g.Cherry,
                new CI(i.WhiteRum, 60M),
                new CI(i.CoconutCream, 20M),
                new CI(i.PineappleJuice, 90M),
                new CI(i.LimeJuice, 15M)),

            new C(c.B52, "B-52", "#460000,#D5C1A9,#E57D00",
                v.Shot, p.Layer, g.None,
                new CI(i.Kahlúa, 20M),
                new CI(i.Baileys, 20M),
                new CI(i.GrandMarnier, 20M)),

            new C(c.Caipirinha, "Caipirinha", "#EDF6B2", onTheRocks,
                v.Rocks, p.Build, g.None,
                new CI(i.Cachaça, 60M),
                new CI(i.Lime, 0.5M, s.Muddle),
                new CI(i.Sugar, 2 * q.Teaspoon, s.Muddle)),

            new C(c.AmarettoSour, "Amaretto Sour", "#AE8333", onTheRocks,
                v.Rocks, p.Shake, g.Cherry,
                new CI(i.Amaretto, 60M),
                new CI(i.LemonJuice, 30M)),

            new C(c.Brooklyn, "Brooklyn", "#912906",
                v.Cocktail, p.Stir, g.Cherry,
                new CI(i.Rye, 60M),
                new CI(i.DryVermouth, 30M),
                new CI(i.Maraschino, 7.5M),
                new CI(i.Angostura, 3 * q.Dash)),

            new C(c.Vodkatini, "Vodkatini", "#F9FAFA",
                v.Cocktail, p.Shake, g.Olive,
                new CI(i.Vodka, 60M),
                new CI(i.DryVermouth, 10M)),

            new C(c.HorsesNeck, "Horse's Neck", "#EAA10A", onTheRocks,
                v.Highball, p.Build, g.LemonTwist,
                new CI(i.Brandy, 40M),
                new CI(i.GingerAle, 120M),
                new CI(i.Angostura, q.Dash)),

            new C(c.BnB, "B&B", "#AC2A1C", onTheRocks,
                v.Rocks, p.Build, g.None,
                new CI(i.Brandy, 60M),
                new CI(i.Benedictine, 60M)),

            new C(c.TiPunch, "Ti' Punch", "#BEA652",
                v.Rocks, p.Build, g.LimeSlice,
                new CI(i.RhumAgricole, 45M),
                new CI(i.LimeJuice, q.Teaspoon, s.Squeeze),
                new CI(i.SimpleSyrup, q.Teaspoon)),

            new C(c.Penicillin, "Penicillin", "#D79C02", onTheRocks,
                v.Rocks, p.Build, g.None,
                new CI(i.Scotch, 50M),
                new CI(i.LemonJuice, 20M),
                new CI(i.HoneySyrup, 20M),
                new CI(i.IslayScotch, q.Teaspoon, s.Float),
                new CI(i.GingerSlice, 3, s.Muddle)),

            new C(c.RumOldFashioned, "Rum Old Fashioned", "#C25003", onTheRocks,
                v.Rocks, p.Build, g.OrangeTwist,
                new CI(i.DarkRum, 60M),
                new CI(i.Angostura, 2 * q.Dash),
                new CI(i.Sugar, q.Teaspoon),
                new CI(i.Water, q.Splash)),

            new C(c.AperolSpritz, "Aperol Spritz", "#E52F02", onTheRocks,
                v.Rocks, p.Build, g.OrangeSlice,
                new CI(i.Prosecco, 90M),
                new CI(i.Aperol, 60M),
                new CI(i.Soda, 30M)),

            new C(c.LastWord, "The Last Word", "#C2CF7D",
                v.Cocktail, p.Shake, g.Cherry,
                new CI(i.Gin, 60M),
                new CI(i.ChartreuseVerte, 60M),
                new CI(i.Maraschino, 60M),
                new CI(i.LimeJuice, 60M)),

            new C(c.ScotchSoda, "Scotch and Soda", "#FDBD3B", onTheRocks,
                v.Rocks, p.Build, g.None,
                new CI(i.Scotch, 60M),
                new CI(i.Soda, 120M)),

            new C(c.RobRoy, "Rob Roy", "#A62301",
                v.Cocktail, p.Stir, g.Cherry,
                new CI(i.Scotch, 50M),
                new CI(i.SweetVermouth, 20M),
                new CI(i.Angostura, q.Dash)),

            new C(c.Bramble, "Bramble", "#AA1518", onTheRocks,
                v.Rocks, p.Build, g.LemonSlice,
                new CI(i.Gin, 40M),
                new CI(i.LemonJuice, 15M),
                new CI(i.SimpleSyrup, 10M),
                new CI(i.Mûre, 15M)),

            new C(c.SingaporeSling, "Singapore Sling", "#FE3503",
                v.Highball, p.Shake, g.Cherry,
                new CI(i.Gin, 30M),
                new CI(i.CherryHeering, 15M),
                new CI(i.Cointreau, 7.5M),
                new CI(i.Grenadine, 10M),
                new CI(i.LimeJuice, 15M),
                new CI(i.Benedictine, 7.5M),
                new CI(i.PineappleJuice, 120M),
                new CI(i.Angostura, q.Dash)),

            new C(c.BloodAndSand, "Blood and Sand", "#963C03",
                v.Cocktail, p.Shake, g.Cherry,
                new CI(i.Scotch, 20M),
                new CI(i.SweetVermouth, 20M),
                new CI(i.CherryHeering, 20M),
                new CI(i.OrangeJuice, 20M)),

            new C(c.BrandyAlexander, "Brandy Alexander", "#A68C79",
                v.Cocktail, p.Shake, g.Nutmeg,
                new CI(i.Cognac, 30M),
                new CI(i.Cacao, 30M),
                new CI(i.Cream, 30M)),

            new C(c.AlabamaSlammer, "Alabama Slammer", "#F36424",
                v.Cocktail, p.Shake, g.OrangeTwist,
                new CI(i.SouthernComfort, 30M),
                new CI(i.Amaretto, 30M),
                new CI(i.SloeGin, 30M),
                new CI(i.OrangeJuice, 60M)),

            new C(c.Vesper, "Vesper", "#EEEEE4",
                v.Cocktail, p.Shake, g.LemonTwist,
                new CI(i.Gin, 60M),
                new CI(i.Vodka, 20M),
                new CI(i.LilletBlanc, 10M)),

            new C(c.CorpseReviver2, "Corpse Reviver #2", "#E7C784",
                v.Cocktail, p.Shake, g.LemonTwist,
                new CI(i.Gin, 20M),
                new CI(i.LemonJuice, 20M),
                new CI(i.Cointreau, 20M),
                new CI(i.LilletBlanc, 20M),
                new CI(i.Absinthe, q.Dash)),

            new C(c.PortoFlip, "Porto Flip", "#B99C8F",
                v.Cocktail, p.Shake, g.Nutmeg,
                new CI(i.Brandy, 15M),
                new CI(i.Port, 45M),
                new CI(i.EggYolk, 10M)),

            new C(c.SexOnTheBeach, "Sex on the Beach", "#E17C19", onTheRocks,
                v.Highball, p.Build, g.OrangeSlice,
                new CI(i.Vodka, 40M),
                new CI(i.PeachSchnapps, 20M),
                new CI(i.OrangeJuice, 40M),
                new CI(i.CranberryJuice, 40M)),

            new C(c.JapaneseSlipper, "Japanese Slipper", "#A6E309",
                v.Cocktail, p.Shake, g.Cherry,
                new CI(i.Midori, 30M),
                new CI(i.Cointreau, 30M),
                new CI(i.LemonJuice, 30M)),

            new C(c.YellowBird, "Yellow Bird", "#FDD847",
                v.Cocktail, p.Shake, g.None,
                new CI(i.WhiteRum, 30M),
                new CI(i.Galliano, 15M),
                new CI(i.TripleSec, 15M),
                new CI(i.LimeJuice, 15M)),

            new C(c.BlueLagoon, "Blue Lagoon", "#12B1EE", onTheRocks,
                v.Highball, p.Build, g.LemonSlice,
                new CI(i.Vodka, 50M),
                new CI(i.BlueCuraçao, 20M),
                new CI(i.Lemonade, 100M)),

            new C(c.SmokyMartini, "Smoky Martini", "#974901",
                v.Cocktail, p.Stir, g.Olive,
                new CI(i.LondonDry, 60M),
                new CI(i.IslayScotch, q.Teaspoon)),

            new C(c.PinkGin, "Pink Gin", "#E48452",
                v.Cocktail, p.Shake, g.LemonTwist,
                new CI(i.PlymouthGin, 60M),
                new CI(i.Angostura, q.Dash)),

            new C(c.GoldenCadillac, "Golden Cadillac", "#C89D3B",
                v.Cocktail, p.Shake, g.None,
                new CI(i.Galliano, 60M),
                new CI(i.Cacao, 60M),
                new CI(i.Cream, 60M)),

            new C(c.FuzzyNavel, "Fuzzy Navel", "#EACC2E", onTheRocks,
                v.Highball, p.Build, g.None,
                new CI(i.PeachSchnapps, 60M),
                new CI(i.OrangeJuice, 120M)),

            new C(c.Millionaire, "Millionaire", "#CA2C32",
                v.Cocktail, p.Shake, g.None,
                new CI(i.SloeGin, 30M),
                new CI(i.ApricotLiqueur, 30M),
                new CI(i.DarkRum, 30M),
                new CI(i.LimeJuice, 30M),
                new CI(i.Grenadine, q.Splash)),

            new C(c.Paradise, "Paradise", "#F5B617",
                v.Cocktail, p.Shake, g.None,
                new CI(i.Gin, 35M),
                new CI(i.ApricotLiqueur, 20M),
                new CI(i.OrangeJuice, 15M)),

            new C(c.Painkiller, "Painkiller", "#F99D21", onTheRocks,
                v.Highball, p.Shake, g.Nutmeg,
                new CI(i.DarkRum, 60M),
                new CI(i.PineappleJuice, 120M),
                new CI(i.OrangeJuice, 30M),
                new CI(i.CoconutCream, 30M)),

            new C(c.Beachcomber, "Beachcomber", "#EBEFEF",
                v.Cocktail, p.Shake, g.LimeSlice,
                new CI(i.WhiteRum, 60M),
                new CI(i.TripleSec, 20M),
                new CI(i.LimeJuice, 20M),
                new CI(i.Maraschino, q.Teaspoon)),

            new C(c.FogCutter, "Fog Cutter", "#DEBC00", onTheRocks,
                v.Highball, p.Shake, g.OrangeSlice,
                new CI(i.WhiteRum, 45M),
                new CI(i.Cognac, 15M),
                new CI(i.Gin, 15M),
                new CI(i.OrangeJuice, 45M),
                new CI(i.LemonJuice, 15M),
                new CI(i.Orgeat, 15M),
                new CI(i.Sherry, 15M, s.Float)),

            new C(c.Mudslide, "Mudslide", "#D9C296", onTheRocks,
                v.Rocks, p.Build, g.None,
                new CI(i.Vodka, 30M),
                new CI(i.Kahlúa, 30M),
                new CI(i.Baileys, 30M)),

            new C(c.Orgasm, "Orgasm", "#E1C4A0", onTheRocks,
                v.Rocks, p.Build, g.None,
                new CI(i.Amaretto, 30M),
                new CI(i.Kahlúa, 30M),
                new CI(i.Baileys, 30M)),

            new C(c.QuickFuck, "Quick Fuck", "#361D10,#398310,#AB854C",
                v.Shot, p.Layer, g.None,
                new CI(i.Kahlúa, 20M),
                new CI(i.Baileys, 20M),
                new CI(i.Midori, 20M)),

            new C(c.Hurricane, "Hurricane", "#C74B00", onTheRocks,
                v.Highball, p.Shake, g.Cherry | g.OrangeSlice,
                new CI(i.DarkRum, 60M),
                new CI(i.WhiteRum, 60M),
                new CI(i.PassionFruitSyrup, 30M),
                new CI(i.PineappleJuice, 30M),
                new CI(i.OrangeJuice, 30M),
                new CI(i.LimeJuice, 15M)),

            new C(c.Scorpion, "Scorpion", "#DEB238", onTheRocks,
                v.Highball, p.Build, g.OrangeSlice,
                new CI(i.WhiteRum, 60M),
                new CI(i.Brandy, 15M),
                new CI(i.OrangeJuice, 60M),
                new CI(i.LemonJuice, 30M),
                new CI(i.Orgeat, 15M)),

            new C(c.Zombie, "Zombie", "#E31F28", onTheRocks,
                v.Highball, p.Shake, g.Cherry,
                new CI(i.WhiteRum, 45M),
                new CI(i.DarkRum, 45M),
                new CI(i.LimeJuice, 15M),
                new CI(i.PineappleJuice, 30M),
                new CI(i.Falernum, 15M),
                new CI(i.Grenadine, q.Splash),
                new CI(i.Angostura, q.Dash)),

            new C(c.BayBreeze, "Bay Breeze", "#B6393D", onTheRocks,
                v.Highball, p.Build, g.LimeSlice,
                new CI(i.WhiteRum, 45M),
                new CI(i.CranberryJuice, 90M),
                new CI(i.PineappleJuice, 30M)),

            new C(c.CapeCodder, "Cape Codder", "#A90808", onTheRocks,
                v.Highball, p.Build, g.LimeSlice,
                new CI(i.Vodka, 60M),
                new CI(i.CranberryJuice, 120M)),

            new C(c.BahamaMama, "Bahama Mama", "#F4530D", onTheRocks,
                v.Highball, p.Shake, g.None,
                new CI(i.DarkRum, 15M),
                new CI(i.CoconutRum, 15M),
                new CI(i.OverproofRum, 15M),
                new CI(i.LemonJuice, 30M),
                new CI(i.PineappleJuice, 120M)),

            new C(c.CornNOil, "Corn N Oil", "#773219", onTheRocks,
                v.Rocks, p.Stir, g.LimeWedge,
                new CI(i.DarkRum, 60M),
                new CI(i.Falernum, 15M),
                new CI(i.Angostura, 2 * q.Dash)),

            new C(c.BlueHawaiian, "Blue Hawaiian", "#01ACD7", onTheRocks,
                v.Highball, p.Shake, g.Cherry,
                new CI(i.WhiteRum, 30M),
                new CI(i.BlueCuraçao, 30M),
                new CI(i.PineappleJuice, 60M),
                new CI(i.CoconutCream, 30M)),

            new C(c.JungleBird, "Jungle Bird", "#D34C24", onTheRocks,
                v.Rocks, p.Shake, g.None,
                new CI(i.DarkRum, 45M),
                new CI(i.Campari, 20M),
                new CI(i.LimeJuice, 15M),
                new CI(i.PineappleJuice, 45M),
                new CI(i.SimpleSyrup, 15M)),

            new C(c.Alaska, "Alaska", "#E4DD89",
                v.Cocktail, p.Stir, g.OrangeTwist,
                new CI(i.Gin, 45M),
                new CI(i.ChartreuseJaune, 15M),
                new CI(i.OrangeBitters, q.Dash)),

            new C(c.Bronx, "Bronx", "#F7BB01",
                v.Cocktail, p.Shake, g.None,
                new CI(i.Gin, 60M),
                new CI(i.SweetVermouth, 10M),
                new CI(i.DryVermouth, 10M),
                new CI(i.OrangeJuice, 30M)),

            new C(c.Bijou, "Bijou", "#D08A0B",
                v.Cocktail, p.Stir, g.OrangeTwist,
                new CI(i.Gin, 30M),
                new CI(i.SweetVermouth, 30M),
                new CI(i.ChartreuseVerte, 30M),
                new CI(i.OrangeBitters, q.Dash)),

            new C(c.AngelFace, "Angel Face", "#ECC74D",
                v.Cocktail, p.Shake, g.None,
                new CI(i.Gin, 30M),
                new CI(i.ApricotLiqueur, 30M),
                new CI(i.Calvados, 30M)),

            new C(c.PeguClub, "Pegu Club", "#D5AD04",
                v.Cocktail, p.Shake, g.LimeSlice,
                new CI(i.Gin, 60M),
                new CI(i.TripleSec, 30M),
                new CI(i.LimeJuice, 10M),
                new CI(i.Angostura, q.Dash),
                new CI(i.OrangeBitters, q.Dash)),

            new C(c.Algonquin, "Algonquin", "#EDBD00",
                v.Cocktail, p.Stir, g.OrangeTwist,
                new CI(i.Rye, 60M),
                new CI(i.DryVermouth, 30M),
                new CI(i.PineappleJuice, 30M)),

            new C(c.BrandyCrusta, "Brandy Crusta", "#A15D15",
                v.Cocktail, p.Shake, g.LemonTwist,
                new CI(i.Cognac, 50M),
                new CI(i.LemonJuice, 15M),
                new CI(i.TripleSec, q.Teaspoon),
                new CI(i.Maraschino, q.Teaspoon),
                new CI(i.SimpleSyrup, q.Teaspoon),
                new CI(i.Angostura, q.Dash)),

            new C(c.Batida, "Batida", "#ECD9B4", onTheRocks,
                v.Highball, p.Shake, g.None,
                new CI(i.Cachaça, 60M),
                new CI(i.FruitJuice, 60M),
                new CI(i.CondensedMilk, 30M, isOptional: true)),
        };
    }
}